# Generated by Django 3.2.15 on 2023-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityitemcolorsize',
            name='photo_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
